### ISSUE TITLE
Not compatible with microservices

### ISSUE THREAD

**Issue by slava-ovchinnikov** [ozkanonur/nestjs-rate-limiter#15]
Response is unavailable when I'm invoking protected by rate-limit controller over TCP microservice.

![image](https://user-images.githubusercontent.com/15925365/91159968-7ee96600-e6d1-11ea-955f-65514cfcd1bd.png)

**Comment by ozkanonur** [comment]
I will be checking on this with the v2 upgrade.Added to #17

**Comment by ozkanonur** [comment]
Closed via #18
