### ISSUE TITLE
Disable rate limiter on specific tests

### ISSUE THREAD

**Issue by Langstra** [ozkanonur/nestjs-rate-limiter#27]
Already mentioned this in a previous issue as a side question, but how would you feel about adding a environment variable (like process.env.disable_rate_limiter) to disable the rate limiter for certain tests or for certain environments/configurations at development time?

**Comment by ozkanonur** [comment]
@Langstra  I deleted the disabling rate limiter by using the environment variable because of some performance issues. Anyway, there is a better way to deal with that. You can use specify your local in whiteList and then you won't get the limiter exceptions anymore.

**Comment by Langstra** [comment]
But is there a way to enable it on runtime again? I would like to write a test suite that tests if the rate limiter is enabled. All my other test suites can have the rate limiter disabled.

**Comment by ozkanonur** [comment]
When ip address values ​​are entered as an array in the whiteList, the rate limiter is disabled for requests from these ip addresses.
For your tests, you can either enter your local address in whiteList for development purpose or you can create an environment variable as WHITE_IP that equals to ip address and use it like:

```ts
whiteList: [process.env.WHITE_IP, '8.8.8.8', 'bla.bla.bla.bla']
```
When you delete WHITE_IP from environment variables, then rate limiter will become normal again.
But what I really recommend is give '127.0.0.1' to whiteList and feel completely free. Like I do [here](https://github.com/feednext/feednext/blob/ref/categories-to-tags/server/src/app.module.ts#L26)

**Comment by Langstra** [comment]
Thanks for thinking along 👍
