### ISSUE TITLE
keyPrefix not working - root module overwritten

### ISSUE THREAD

**Issue by kevinsproles** [ozkanonur/nestjs-rate-limiter#28]
I registered the RateLimiterModule globally in one place.

````typescript
@Module({
  imports: [
    RateLimiterModule.register({
      // default rate limit for all endpoints
      keyPrefix: 'global',
      points: 7, // 7 requests
      duration: 60, // per 60 seconds per IP
      errorMessage: 'You hit the global limit',
    }),
  ],
  providers: [
    {
      provide: APP_INTERCEPTOR,
      useClass: RateLimiterInterceptor,
    },
  ],
})
````

I'm using the decorator inside my controllers to create unique limits for specific endpoints.

````typescript
  @RateLimit({
    keyPrefix: 'users',
    points: 2, // 2 requests
    duration: 60, // per 60 seconds per IP
    errorMessage: 'Users cannot be queried more than twice per minute',
  })
````

### Here's what happens:

You can hit any of the other endpoints (4 times one of them, 3 times another) and on the 8th time you'll get:
````javascript
{
statusCode: 429,
error: "Too Many Requests",
message: "You hit the global limit"
}
````
And at this point you cannot hit any endpoints, except **you can** still hit the /users endpoint. Because of the keyPrefix being different. On your 3rd try you'll get:
````javascript
{
statusCode: 429,
error: "Too Many Requests",
message: "Users cannot be queried more than twice per minute"
}
````
All good so far.

### 1st problem
If you now hit any other endpoint you'll no longer see "you hit the global limit" message. You'll now see "Users cannot be queried more than twice per minute".

### 2nd problem
If you start over, and this time you first hit the /users endpoint 3 times. It will trigger the message "Users cannot be queried more than twice per minute". All good. But now go to any other endpoint and **it should** let you because it's using the 'global' keyPrefix. But it doesn't let you, and in fact tells you you hit the "Users cannot be queried more than twice per minute".

**Comment by ozkanonur** [comment]
Thank you for telling me this issue with a crystal clear explanation. I am working on it right now. @kevinsproles

**Comment by kevinsproles** [comment]
I can confirm it's fixed, thank you @ozkanonur 🙏
