### ISSUE TITLE
Base limit on accesstoken

### ISSUE THREAD

**Issue by T00rk** [ozkanonur/nestjs-rate-limiter#32]
I would like to limit request to my api to 1 request per second per user. It should be based on the authorization token.
Is there any option to do it using nestjs-rate-limiter ?

**Comment by ozkanonur** [comment]
@T00rk  I will add this feature as soon as I get rid of covid-19. Currently this feature is unfortunately not supported.

**Comment by T00rk** [comment]
Thank you for your answer. I was not aware you are suffering from covid. I wish you a speedy recovery.

**Comment by ozkanonur** [comment]
@T00rk I thought I found a way to do this. I thought if you provide different keyPrefix for each user, like if you give user-id as keyPrefix then they will get their own rate limitation. However, NestJS's interceptors not allowing us to do this. Your first initialization value will stay permanently on your applied endpoint. As an example, if you say keyPrefix: Math.random() you will get the same value for all the requests that hit the endpoint. Not sure if I can find a workaround about this but I will be trying.

**Comment by iamruslanbakirov** [comment]
@ozkanonur i need this ability too)

**Comment by iamruslanbakirov** [comment]
actually, i need two type at the same time
first is base on ip, and second is base on an access token after autorization

**Comment by ozkanonur** [comment]
This issue is related to Nest's core feature. Cant use dynamic variables on decorator of interceptors. Closed for now

**Comment by somehowchris** [comment]
How about () => Math.random() instead of just Math.random()?

**Comment by ozkanonur** [comment]
> How about () => Math.random() instead of just Math.random()?

I will check it later today or you can check and tell me the result

**Comment by somehowchris** [comment]
> > How about () => Math.random() instead of just Math.random()?
> 
> I will check it later today or you can check and tell me the result

Well works for me. Used the basic example which allows you to have 1 req/s but with `() => Math.random()` it allows me to do it again and again until that random is matched. This isn't a nestjs thing bug rather a js object initialization thing

**Comment by ozkanonur** [comment]
> > > How about () => Math.random() instead of just Math.random()?
> > 
> > 
> > I will check it later today or you can check and tell me the result
> 
> Well works for me. Used the basic example which allows you to have 1 req/s but with `() => Math.random()` it allows me to do it again and again until that random is matched. This isn't a nestjs thing bug rather a js initialization thing and functions do only get initialized as they are run

perfect then, I will implement the feature soon like tomorrow or tuesday. Thanks for the feedback, appreciate it.

**Comment by ccomandini** [comment]
hey @ozkanonur any news on this ?

**Comment by ozkanonur** [comment]
you can do it by giving different <code>[keyPrefix](https://github.com/ozkanonur/nestjs-rate-limiter#-keyPrefix)</code> to each user. The keyPrefix could be their access token. @ccomandini
