### ISSUE TITLE
Introduce Rate Limiter Interface unit tests

### ISSUE THREAD

**Issue by shannonlal** [ozkanonur/nestjs-rate-limiter#36]
@ozkanonur Following up on my previous Issue and PR about refactoring some of the code and include some unit tests.  @ozkanonur if you are open to this I can submit another PR. 

If you are okay I will add more documentation here on how it could be refactored but I wanted to run this by you first to see if it would be valuable.

Thanks

**Comment by ozkanonur** [comment]
@shannonlal  Yes, that would be awesome. Once you finish the tests, I can/will build the ci&cd setup. Thank you for contributing to this project and reducing the workload on me.

**Comment by shannonlal** [comment]
Refactoring this Issue into smaller issues so that it is easier to merge the changes in.  This small issue will be focused on including unit tests for the interface typescript
