### ISSUE TITLE
Cannot read property 'limiterKey' of undefined

### ISSUE THREAD

**Issue by dfp961214** [ozkanonur/nestjs-rate-limiter#47]
Cannot read property 'limiterKey' of undefined

**Comment by dfp961214** [comment]
I found it in default-options.js, you did not update the relevant configuration of limiterKey to README.md

**Comment by ozkanonur** [comment]
Its an alpha version, so you can't see its documentation on the master branch

**Comment by te-online** [comment]
Well, alpha version seems to get installed as `latest` on npm that might be why this happened 😉
