### ISSUE TITLE
Will it work with NestJs using Fastify?

### ISSUE THREAD

**Issue by anwaar931** [ozkanonur/nestjs-rate-limiter#5]
```
[Nest] 76   - 10/24/2019, 9:16:33 AM   [ExceptionsHandler] response.set is not a function +807ms
TypeError: response.set is not a function
at RateLimiterInterceptor.<anonymous> (/usr/src/service/service-api/node_modules/nestjs-rate-limiter/dist/rate-limiter.interceptor.js:126:26)
```

It throws this error.

**Comment by RyanTheAllmighty** [comment]
I'll take a look.

I only tested with the default express implementation. I'll take a look at Fastify and try and identify the issue and at minimum make a note in the README

**Comment by ozkanonur** [comment]
Until this repository supports fastify, anybody who wants to use this package on fastify can install from https://github.com/feednext/nestjs-rate-limiter with `npm i --save feednext/nestjs-rate-limiter#build`. Nothing changed for usage wise, @RyanTheAllmighty take a look at what I have changed and implement it to this package when you have time. I think you should take parameter on initialization like 'express' or 'fastify' and do the job conditionally in interceptor.

**Comment by ozkanonur** [comment]
Also, custom error message support added

**Comment by ozkanonur** [comment]
Moved to #17
