### ISSUE TITLE
Ability to override response

### ISSUE THREAD

**Issue by panalgin** [ozkanonur/nestjs-rate-limiter#60]
Hi,

I think it would be a nice addition if we could override the errorMessage not just as a string but also completely in terms of the structure. Currently, rate-limiter returns a basic HttpException(with default or custom message user sets).

How about when we would like to override the default exception message with a json body?

**Comment by evle** [comment]
@ozkanonur it's a good idea, something like  createErrorBody provides by nestjs-ratelimiter
