### ISSUE TITLE
Provide a guard instead of interceptor

### ISSUE THREAD

**Issue by pedrosodre** [ozkanonur/nestjs-rate-limiter#72]
Hey there,

I want to know if there is any specific reason to use an interceptor to do the rate limiting instead of a guard (or have both). The reason I'm asking it is because the nest's execution order. That is what Nest does per each request:

> 1. Incoming request
> 2. Globally bound middleware
> 3. Module bound middleware
> 4. Global guards
> 5. Controller guards
> 6. Route guards
> 7. Global interceptors (pre-controller)
> 8. Controller interceptors (pre-controller)
> 9. Route interceptors (pre-controller)
> 10. Global pipes
> 11. Controller pipes
> 12. Route pipes
> 13. Route parameter pipes
> 14. Controller (method handler)
> 15. Service (if exists)
> 16. Route interceptor (post-request)
> 17. Controller interceptor (post-request)
> 18. Global interceptor (post-request)
> 19. Exception filters (route, then controller, then global)
> 20. Server response

If I have a guard to authenticate user, rate limit the endpoint with an interceptor will allow a brute-force attack, since I'll always receive guard's exception when password is incorrect.

Does my question make sense?

Cheers

**Comment by ozkanonur** [comment]
> Hey there,
> 
> I want to know if there is any specific reason to use an interceptor to do the rate limiting instead of a guard (or have both). The reason I'm asking it is because the nest's execution order. That is what Nest does per each request:
> 
> > 1. Incoming request
> > 2. Globally bound middleware
> > 3. Module bound middleware
> > 4. Global guards
> > 5. Controller guards
> > 6. Route guards
> > 7. Global interceptors (pre-controller)
> > 8. Controller interceptors (pre-controller)
> > 9. Route interceptors (pre-controller)
> > 10. Global pipes
> > 11. Controller pipes
> > 12. Route pipes
> > 13. Route parameter pipes
> > 14. Controller (method handler)
> > 15. Service (if exists)
> > 16. Route interceptor (post-request)
> > 17. Controller interceptor (post-request)
> > 18. Global interceptor (post-request)
> > 19. Exception filters (route, then controller, then global)
> > 20. Server response
> 
> If I have a guard to authenticate user, rate limit the endpoint with an interceptor will allow a brute-force attack, since I'll always receive guard's exception when password is incorrect.
> 
> Does my question make sense?
> 
> Cheers

Hello there, thank you for your feedback.
No, there is no specific reason that requires to use interceptors on this library. The reason that we have interceptor here is I did not create this package, I took it over. When I took over, it was built on the interceptor. There were functions that were much more important to provide, I gave priority to them. From now on, we can make the library work based on Nest's Guards.

**Comment by pedrosodre** [comment]
Amazing, thanks for your return @ozkanonur . Let me know if you need any help to make this happen, I'm up to contribute :)

**Comment by ozkanonur** [comment]
Anybody can contribute to this library, PRs are open so just let me know if you want to do it. @pedrosodre

**Comment by ozkanonur** [comment]
Done by #80
