### ISSUE TITLE
Do we have option to pass typeorm for store client?

### ISSUE THREAD

**Issue by karthikeyan-cere** [ozkanonur/nestjs-rate-limiter#74]
I am using Typeorm in my application for communicating with the Database. Do we have an option to pass the Typeorm to the store client? If yes, can you please point me to the examples?

**Comment by ozkanonur** [comment]
@karthikeyan-cere  Did you try giving return value of <code>createConnection</code> ? If it doesn't work then I should probably release a new version on npm.

**Comment by ozkanonur** [comment]
Issue closed due to inactivity.
