### ISSUE TITLE
Multiple buckets for same API

### ISSUE THREAD

**Issue by aesher9o1** [ozkanonur/nestjs-rate-limiter#75]
node-rate-limiter-flexible allows `[handling traffic bursts with Bursty Rate Limits](https://github.com/animir/node-rate-limiter-flexible/wiki/BurstyRateLimiter)`. Do we have a provision to do the same in the library?
![image](https://user-images.githubusercontent.com/29084675/124547913-8c6f9080-de4a-11eb-9ffa-feaa5cdb65dc.png)

**Comment by ozkanonur** [comment]
@aesher9o1  Yes, we also have keyPrefix that applies the same logic.
